@startuml

scale 800*800

skinparam defaultFontName "Noto Sans Mono CJK TC Regular"

abstract class 形狀 {
    + 顯示()
}

abstract class 長方形{
    {abstract} #畫線()
    + 顯示()
}

class 長方形V1 {
    # 畫線()
}

class 長方形V2 {
    # 畫線()
}

abstract class 圓形 {
    {abstract} # 畫圓()
    + 顯示()
}

class 圓形V1 {
    # 畫圓()
}

class 圓形V2 {
    # 畫圓()
}

class GDIPlus{
    + 畫線()
    + 畫圓()
}

class Win32API{
    + 畫直線()
    + 畫圓形()
}

長方形 <|-down- 長方形V1
長方形 <|-down- 長方形V2

長方形V1 -down-> GDIPlus 
長方形V2 -down-> Win32API

圓形 <|-down- 圓形V1
圓形 <|-down- 圓形V2

圓形V1 -down-> GDIPlus
圓形V2 -down-> Win32API

形狀 <|-down- 長方形
形狀 <|-down- 圓形

@enduml