@startuml

skinparam defaultFontName "Fira Code"
skinparam class {
    FontStyle bold
    FontSize 12
}

scale 800*800

interface Observable{
    +registerObserver()
    +notifyObservers()
}

class CascadingComboBox{
    -onChange
}

Observable <|-down- CascadingComboBox
CascadingComboBox --o CascadingComboBox

@enduml