@startuml

scale 800*800

skinparam defaultFontName "Noto Sans Mono CJK TC Regular"

class Client{    
}

class Target {
    +request()
}

class Adaptor {    
    +request()
}

class Adaptee {
    +specificRequest()
}

Client -right-> Target
Target <|-down- Adaptor
Adaptor -> Adaptee : "adptee"

@enduml