@startuml

scale 800*800

skinparam defaultFontName "Noto Sans Mono CJK TC Regular"


abstract class 形狀 {
    + 設定位置()
    + 取得位置()
    {abstract} 顯示()
    {abstract} 填滿()
    {abstract} 設定顏色()
    隱藏()        
}

class 點 {
    + 顯示()
    + 填滿()
    + 設定顏色()
}

class 線 {
    + 顯示()
    + 填滿()
    + 設定顏色()
}

class 方形 {
    + 顯示()
    + 填滿()
    + 設定顏色()
}

class 圓形 {
    + 設定位置()
    + 取得位置()
    + 顯示()
    + 填滿()
    + 設定顏色()
    + 隱藏()        
}

class 吉米的圓形 {
    + 設定位置()
    + 取得位置()
    + 顯示()
    + 填滿顏色()
    + 設定它的顏色()
    + 隱藏()  
}

形狀 <|-- 圓形
形狀 <|-- 點
形狀 <|-- 線
形狀 <|-- 方形
圓形 *-left- 吉米的圓形

使用者 -right-> 形狀

@enduml