@startuml

scale 800*800

skinparam defaultFontName "Noto Sans CJK TC Regular"

interface 三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

class 火腿蛋三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

class 鮪魚蛋三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

class 三明治工廠 {
    + 三明治 製作三明治(String 種類)
}

三明治 <|.. 火腿蛋三明治
三明治 <|.. 鮪魚蛋三明治
三明治工廠 .right.> 三明治

@enduml