@startuml

scale 800*800

skinparam defaultFontName "Noto Sans Mono CJK TC Regular"

[*] -down-> 欄位開始
欄位開始 --> [*] : 行結束
欄位開始 -> 掃描雙引號欄位 : 雙引號
欄位開始 --> 掃描欄位 : 不是雙引號或逗號
掃描欄位 -> 欄位開始 : 逗號
掃描欄位 -> 掃描欄位 : 不是逗號
掃描欄位 -> [*] : 行結束
掃描雙引號欄位 -down-> 雙引號欄位結束 : 雙引號
掃描雙引號欄位 -> 掃描雙引號欄位 : 不是逗號
雙引號欄位結束 -> [*] : 不是逗號
雙引號欄位結束 -down-> [*] : 行結束
雙引號欄位結束 -> 欄位開始 : 逗號
@enduml