@startuml

scale 2048*2048

skinparam defaultFontName "Noto Sans CJK TC Regular"

interface 三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

class 火腿蛋三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

class 鮪魚蛋三明治 {
	+ 烤麵包()
	+ 抹醬料()
	+ 煎蛋()
	+ 加料()
	+ 包裝()
}

interface 三明治工廠 {
    + 三明治 製作三明治()
}

class 火腿蛋三明治工廠{
    + 三明治 製作三明治()
}

class 鮪魚蛋三明治工廠{
    + 三明治 製作三明治()
}

三明治 <|.. 火腿蛋三明治
三明治 <|.. 鮪魚蛋三明治
三明治工廠 ..> 三明治
三明治工廠 <|.down. 火腿蛋三明治工廠
三明治工廠 <|.down. 鮪魚蛋三明治工廠

@enduml